import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const josefin = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "RentEase - Where Trust Meets Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${josefin.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
          {children}
          <ToastContainer autoClose={2000} />
      </body>
    </html>
  );
}
